### ISSUE TITLE
Share buttons

### ISSUE THREAD

**Issue by jarrekk** [ashutoshmjain/homepage#1]
Hi Amj,

I am very glad you have posted some blogs to your website and I see you add share buttons yourself, yesterday I found a website <https://www.addtoany.com/> where can custom share buttons, I have used it to my website, following url is a blog is about newest update and also has share buttons on it. I hope it can help you. <http://www.jack003.com/html/2017/01/28/3-steps-to-setup-website-with-Jalpc.html>

Thanks.

**Comment by ashutoshmjain** [comment]
Thanks @JiaKunUp - This is very helpful  .. I will implement your code  ..

**Comment by ashutoshmjain** [comment]
Worked like a charm .. thanks a ton
